### ISSUE TITLE
Archive?

### ISSUE THREAD

**Issue by marcoscaceres** [mikewest/hsts-priming#6]
This incubation seems to have run its course... should we archive? @mikewest ?

**Comment by mikewest** [comment]
Mozilla did some experimentation with this mechanism, and decided not to ship it. Google is pursuing the proposals in https://github.com/mikewest/webappsec-mixed-content/blob/master/proposed-level-2-roadmap.md#proposals. No one is looking at this mechanism anymore; archiving it seems reasonable.

I don't suppose there's a template for that in WICG? Should there be?

**Comment by marcoscaceres** [comment]
> I don't suppose there's a template for that in WICG? Should there be?

Not exactly, as it's somewhat unique for each incubation (some mutate into new things, others die on the vine, some become new feature policy things... and so on...). I've been just adding something to the README.md explaining what happened and that incubation has stopped.

**Comment by marcoscaceres** [comment]
Updated README.md quoting https://github.com/WICG/hsts-priming/issues/6#issuecomment-505102310 ... will archive.
